### ISSUE TITLE
Cannot use either nhanes_data_files or nhanes_variables functions

### ISSUE THREAD

**Issue by Thomas-Richardson** [SilentSpringInstitute/RNHANES#13]
When I run either:

files <- nhanes_data_files()
variables <- nhanes_variables() 

I get : 

trying URL 'https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Demographics'
Content type 'text/html; charset=utf-8' length 1382905 bytes (1.3 MB)
downloaded 1.3 MB

Error in dat[[2]] : subscript out of bounds

**Comment by herbps10** [comment]
Thomas - are you running the latest version from Github? I think I fixed this issue in the Github version.

```
devtools::install_github("SilentSpringInstitute/RNHANES")
library(RNHANES)
```

Let me know if that doesn't work.

**Comment by kintany** [comment]
@herbps10  I have the same issue, using the latest version from github

**Comment by snaik** [comment]
Same issue - Latest version from github doesn't help either...

**Comment by herbps10** [comment]
If I run the following code I don't receive any errors:

```
devtools::install_github("SilentSpringInstitute/RNHANES")

library(RNHANES)

files <- nhanes_data_files()
variables <- nhanes_variables()
```

can you confirm this does not work for you?

**Comment by xiaosongz** [comment]
I test the code above, and it works fine for me. 

```
> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Catalina 10.15.3      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Detroit             
 date     2020-02-14  
```

**Comment by maurosc3ner** [comment]
Hi,

I confirm the devtools command also worked for me 

Thanks

**Comment by xiaosongz** [comment]
> When I run either:
> 
> files <- nhanes_data_files()
> variables <- nhanes_variables()
> 
> I get :
> 
> trying URL 'https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Demographics'
> Content type 'text/html; charset=utf-8' length 1382905 bytes (1.3 MB)
> downloaded 1.3 MB
> 
> Error in dat[[2]] : subscript out of bounds

I am encountering this problem again now. The issue won't be solved just by install from GitHub `devtools::install_github("SilentSpringInstitute/RNHANES")` and reload the package, I closed my R session then restart RStudio/R completely and the error went away. 

my guess is some of the function still trying to read files cached on the disk created by the CRAN version of this package(which is not created correctly) if you do not restart R.

**Comment by gerdaya** [comment]
> 
> 
> > When I run either:
> > files <- nhanes_data_files()
> > variables <- nhanes_variables()
> > I get :
> > trying URL 'https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Demographics'
> > Content type 'text/html; charset=utf-8' length 1382905 bytes (1.3 MB)
> > downloaded 1.3 MB
> > Error in dat[[2]] : subscript out of bounds
> 
> I am encountering this problem again now. The issue won't be solved just by install from GitHub `devtools::install_github("SilentSpringInstitute/RNHANES")` and reload the package, I closed my R session then restart RStudio/R completely and the error went away.
> 
> my guess is some of the function still trying to read files cached on the disk created by the CRAN version of this package(which is not created correctly) if you do not restart R.

I have the same issue.

**Comment by herbps10** [comment]
@gerdaya if you install the Github version and restart R do you still get the same error message?

**Comment by gerdaya** [comment]
I actully failed to install the Github version. Error reported: Failed to install 'RNHANES' from GitHub:
  Timeout was reached: [api.github.com] Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
