### ISSUE TITLE
2017-2020 cycle load error due to improper suffix handling

### ISSUE THREAD

**Issue by ThomasKraft** [SilentSpringInstitute/RNHANES#16]
There exists an issue (example below) in which combined files from the 2017-2020 NHANES cycle cannot be loaded with the usual `RNHANES` functions:

```
paq <- nhanes_load_data("P_SLQ", "2017-2020", demographics = TRUE, cache=F). # error, tries to load "P_SLQ_.XPT"
```

This error appears to stem from the changed naming convention format of the combined 2017-2020 cycle. As far as I can tell, the error occurs because of the way in which RNHANES tries to recognize a problem in the filename and appends a suffix:
https://github.com/SilentSpringInstitute/RNHANES/blob/1cb3cbf7188e5a5a304b881bf9bdb416af744e51/R/import.R#L191

A simple fix perhaps would be to recognize the "P_" cycle and ignore the name checks?

**Comment by herbps10** [comment]
Hello,
Thanks for the report. As a workaround while I fix this, try running:

`paq <- nhanes_load_data("P_SLQ.XPT", "2017-2018", demographics = TRUE, cache=F)`

Adding the ".XPT" to the end of the file file being requested causes RNHANES to not do any manipulation of the file name. Let me know if that doesn't work.

**Comment by ThomasKraft** [comment]
Ah yes of course that works! thanks @herbps10 !

**Comment by workingonstuff** [comment]
This is patched now. Naming extensions with XPT still works, but package now recognizes the 2017-2020 cycle and properly appends the prefix the download links use.
