### ISSUE TITLE
Issue downloading files in RStudio Server

### ISSUE THREAD

**Issue by yknot** [SilentSpringInstitute/RNHANES#4]
I'm having an issue running the `nhanes_data_files()` function. The exact error is shown below, it seems to be when using `download.file` and more specifically the `method = 'auto'` portion. If I take out that part and let `download.file` select the method there is no error and it downloads fine. I'm not well versed in `download.file` so I don't know if that needs to stay `method = 'auto'` or not, but I figured I would bring it to your attention. If this can't be changed I can always fork the repo. Thanks.

```
> files <- nhanes_data_files()
Downloading NHANES data file list to /tmp/RtmpAPJ4To/file709c1de6be7c
trying URL 'https://wwwn.cdc.gov/Nchs/Nhanes/Search/DataPage.aspx?Component=demographics'
Error in download.file(url, destination, method = "auto", mode = "wb") : 
  cannot open URL 'https://wwwn.cdc.gov/Nchs/Nhanes/Search/DataPage.aspx?Component=demographics'
In addition: Warning message:
In download.file(url, destination, method = "auto", mode = "wb") :
  URL 'https://wwwn.cdc.gov/Nchs/Nhanes/Search/DataPage.aspx?Component=demographics': status was 'Problem with the SSL CA cert (path? access rights?)'
```

https://github.com/SilentSpringInstitute/RNHANES/blob/62d99731e11ac052d228cadbfc95765c6bdf1c1c/R/variables.R#L32

https://github.com/SilentSpringInstitute/RNHANES/blob/62d99731e11ac052d228cadbfc95765c6bdf1c1c/R/variables.R#L138

**Comment by herbps10** [comment]
Thanks! I've had problems with download.file in the past too. I'll look into this today.

**Comment by herbps10** [comment]
I added an argument to `nhanes_data_files` for manually setting the method to use with `download.file`. 

So you can do `nhanes_data_file(method = 'internal')` or `nhanes_data_file(method = 'curl')`, etc. (all possible methods are listed here https://stat.ethz.ch/R-manual/R-devel/library/utils/html/download.file.html) and you should be able to find one that will work. I think `method="auto"` is the default, so I'm not sure why removing the method argument made it work for you. 

Let me know if this doesn't fix your problem. Thanks!

**Comment by yknot** [comment]
Perfect that works for me. I did see after I posted that `method` doesn't have a default value so I don't know why removing it worked for me. I needed to set `method="curl"` so maybe something was doing that by default for me.

Thanks for your help!

**Comment by xiaosongz** [comment]
I found this issue yesterday too!!! Which I did not encounter a few days ago?

I dug a little for this issue and I found it happens only when `method = "libcurl"`

manually assign `method` works for `nhanes_load_data()`, but not seems working for `nhanes_data_files()`, since `method` is not passed to `parse_data_files_page()` in `lapply()`

**Comment by xiaosongz** [comment]
Sorry, I just saw you fix the method override issue yesterday! Thank you!

**Comment by xiaosongz** [comment]
Hi Herb,

Sorry to bother you again, but I notice this quick fix for the method only fix the downloading for `nhanes_data_files()`. But the same SSL CA issue still exist when trying to pull multiple files from CDC by feeding the `nhanes_load_data()` with a list of file_names and cycles, the `method` argument seems not passed to the `download.file()`.
