### ISSUE TITLE
Cannot download BPX data after 2011-2012

### ISSUE THREAD

**Issue by jenineharris** [SilentSpringInstitute/RNHANES#7]
Hello, I have used the following code structure successfully before to download and use other data files from the RNHANES package, but I cannot seem to get 2015-2016 files to load in. Has something changed:

nhanes2016 <- nhanes_load_data("BPX_I", "2015-2016", demographics = TRUE)

I get an "Invalid year: 2015-2016" Error in validate_year(year).

I am able to open the data directly from the URL:  https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BPX_I.XPT

Thanks!

**Comment by herbps10** [comment]
Hi,
Are you using the CRAN version of the package? If so, can you try using the latest version on Github? I think this issue was fixed, but I haven't gotten around to updating the CRAN version.

```
devtools::install_github("silentspringinstitute/RNHANES")
```
Let me know if you still have trouble.

Thanks

**Comment by jenineharris** [comment]
Yes that seems to do the trick. Thanks!

**Comment by jonesparg** [comment]
Hi,
I am having problems accessing 2015-16 data, despite using the version of RNHANES obtained from github.  It is possible that some elements of the package did not compile.  Is there any workaround?
Many thanks for any help you are able to offer.

**Comment by ck2136** [comment]
> 
> 
> Hi,
> I am having problems accessing 2015-16 data, despite using the version of RNHANES obtained from github. It is possible that some elements of the package did not compile. Is there any workaround?
> Many thanks for any help you are able to offer.

Had the same issue but after restarting R got it to work :)

**Comment by nadavrap** [comment]
Why won't you publish this newer version on CRAN?

**Comment by gadeelashashi** [comment]
Hi 
I have the latest R version 3.6.1, still i am facing error while downloading latest version from Github

devtools::install_github("silentspringinstitute/RNHANES")
Error: Failed to install 'RNHANES' from GitHub:
  Command not found @win/processx.c:977

Can someone suggest a work around please. Thanks
