### ISSUE TITLE
nhanes_survey will not run svyvar

### ISSUE THREAD

**Issue by earlytm** [SilentSpringInstitute/RNHANES#8]
When I run the following code I receive the error 

"Error in as.vector(survey_fun(formula, ..., design = des)) : 
  object 'svyvar' not found"

I have checked the survey package to ensure that svyvar is, in fact, the correct argument. ANy help fixing this issue would be greatly appreciated.

library(tidyverse)
library(devtools)
install_github("silentspringinstitute/RNHANES", force = TRUE)
require(RNHANES)
require(survey)

phth_data <- nhanes_load_data("PHTHTE", "2013-2014", demographics = TRUE)
phth_data[,48] <- ifelse(phth_data[,48] >= 2, 1, 0)

nhanes_survey(svyvar, phth_data, column = "URXCNP",
              comment_column = "URDCNPLC",
              weights_column = "WTSB2YR", 
              filter = INDFMPIR==0 & RIDRETH3==1, 
              analyze = "values")

**Comment by herbps10** [comment]
Thanks for submitting the issue and an example.

I just ran your example and it works on my computer.

What version of R are you using? You can run `version` in R and paste the results here.

**Comment by earlytm** [comment]
Thank you for your feedback.

I have now been able to get the code to run by running library(survey) before I run library(rnhanes). However, the results include an NA. See below:

 value     cycle begin_year end_year file_name column weights_column comment_column
1    NA 2013-2014       2013     2014  PHTHTE_H URXCNP        WTSB2YR       URDCNPLC

Do you have any idea why the value is being returned as NA?

**Comment by herbps10** [comment]
That's probably because the data has NAs in it, and by default svyvar is returning an NA if there are any NAs in the input.

Try this:

nhanes_survey(svyvar, phth_data, column = "URXCNP",
comment_column = "URDCNPLC",
weights_column = "WTSB2YR",
filter = INDFMPIR==0 & RIDRETH3==1,
analyze = "values", na.rm = TRUE)
